version: '3.9'
services:
  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
networks:
  mongodb:
    driver: bridge
volumes:
  mongo: